// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(ApiContexto))]
    [Migration("20210130172746_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Dominio.Entities.ResultConsumeApiExternal", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Active");

                    b.Property<string>("City");

                    b.Property<string>("CityCode");

                    b.Property<int>("Confirmed");

                    b.Property<string>("Country");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasMaxLength(2);

                    b.Property<DateTime>("Date");

                    b.Property<int>("Deaths");

                    b.Property<string>("Lat")
                        .IsRequired();

                    b.Property<string>("Lon")
                        .IsRequired();

                    b.Property<string>("Province");

                    b.Property<int>("Recovered");

                    b.HasKey("ID");

                    b.ToTable("ResultConsumeApiExternals");
                });
#pragma warning restore 612, 618
        }
    }
}
